### ISSUE TITLE
A couple of questions about the MAX3232 used

### ISSUE THREAD

**Issue by bodiroga** [s00500/homie_benq#1]
Hi Lukas (@s00500)!

First of all, congratulations and thank you for open sourcing your project, it's great to see what others have done using the Homie protocol :wink: I'm trying to make the same thing you have done, but my goal is to control a Marantz SR5001 ([RS232 codes](http://us.marantz.com/DocumentMaster/US/SR5001_RS232_Control_Spec_MAI_V100.pdf)) audio receiver instead of a Benq projector. Sadly I'm having some troubles, so can I make you a couple of questions?

- What MAX3232 are you using in your project? This is the one I am currently using ([link](https://www.ebay.es/itm/RS232-To-TTL-Converter-Module-MAX3232-con-LED/272536652971?hash=item3f74734cab:g:ra8AAOSwcvdXOY3L)), is it similar to yours?
- Seeing your code (your are using the Serial.swap() function), I suppose that you have connected the RX and TX pins of the MAX3232 to the D7 and D8 pins of the ESP8266 (I'm using a NodeMCU board), am I right?

That's all, many thanks for your help! I will continue trying to finish my project.

Best regards,

Aitor

**Comment by s00500** [comment]
Hey @bodiroga I am using the plain MAX232 chip, it is a very comon part you can get it at RSComponents, or farnel or in any good electronics store. https://en.wikipedia.org/wiki/MAX232

Yes I am using D7 and 8, also using the NodeMCU devboard 1.0

Hope I could resolve your questions,
Best Regards Lukas
